In [1]:
import numpy as np

matr = np.random.randint(1, 51, size=(4, 4))
print("Матрица:")
print(matr)

print("Суммы по строкам:", np.sum(matr, axis=1))
print("Суммы по столбцам:", np.sum(matr, axis=0))
print("Общее среднее:", round(np.mean(matr), 2))

Матрица:
[[ 5 34 36 46]
 [26 13 20 44]
 [31  5 29 17]
 [24  8  4 48]]
Суммы по строкам: [121 103  82  84]
Суммы по столбцам: [ 86  60  89 155]
Общее среднее: 24.38


In [2]:
massiv = np.arange(15).reshape(3, 5)
print("Исходный массив:")
print(massiv)

print("\nТранспонированный массив:")
print(massiv.T)

print("\nМассив после reshape:")
print(massiv.reshape(5, 3))

Исходный массив:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

Транспонированный массив:
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]

Массив после reshape:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


# Отчёт по продажам
*В этом разделе мы считаем итоги по простым данным.*

In [3]:
sales = [120, 135, 100, 150, 90, 200, 170]

print("Сумма:", sum(sales))
print("Среднее:", round(sum(sales) / len(sales), 2))
print("Максимум:", max(sales))
print("Минимум:", min(sales))

Сумма: 965
Среднее: 137.86
Максимум: 200
Минимум: 90


| Показатель | Значение |
| :--- | :--- |
| Общая сумма | 965 |
| Среднее | 137.86 |
| Максимум | 200 |
| Минимум | 90 |